### PR TITLE
Pottery Wheel & Gravel Macro Added plus Veg_Janitor updated as 3 seperate commits

### PR DESCRIPTION
**Pull request by RhaomATITD**

### CODE REVIEW

**Comment by Jimbly** [comment]
Pull requests are based off of a branch, so you just (maybe unintentionally) added something more to this PR when you pushed to your master branch.  You can push your head to a new branch (from Git command line) with "git push origin master:new_branch", and then make a PR from that.

Though, if you were trying to just split into 3 commits, not 3 PRs, then what you did was fine =).

**Comment by RhaomATITD** [comment]
I was trying to do 3 PR initially but I guess this works too because each commit has its own ID so they are unique changes :)

**Comment by Jimbly** [comment]
One PR should be fine if all of the changes are good, one of the active ATITD scripters should approve the PR though - @taralx, @ldobson?

**Comment by taralx** [comment]
Veg change looks fine. The gravel script would benefit from using more standard tools, like Ctrl-Shift aborts, but that shouldn't block its inclusion.

**Comment by RhaomATITD** [comment]
The gravel macro is from T7 and obviously I have not had a chance to check it works correctly yet so if you don't want to include feel free to remove it, it is likely it could do with an update

**Comment by ldobson** [comment]
No issues with the gravel macro, I'd just maybe ask that it be renamed to something like stoneDropper.lua so that people don't get confused and think it does more than it does

**Comment by Cegaiel** [comment]
Looks fine to me; the name gravel fits just fine. It looks like it in addition to dropping the stone, provides an easy way to further smash the rock into smaller pieces, eventually to gravel.

**Pull request merged**
