### PR TITLE
Create Gather_Resources.lua

### PR DESCRIPTION
**Pull request by Cyzygy06**
This combines Grass, Slate, and Clay gathering into a single script.  It will look for the gather icons on either side of the screen and both normal and small icons.

### CODE REVIEW

**Comment by Cyzygy06** [comment]
clay_small
slate_small
grass_small

**Comment by Cegaiel** [comment]
I took a shot in the dark and tried @Cyzygy06 in Discord and it matched up to 'Darkfyre'.
I reached out to that player via Discord to see if they could send those _small images, referenced in the .lua file...

**Comment by Cegaiel** [comment]
Successful contact with player. They will check on missing images later, when they get home.

**Comment by Jimbly** [comment]
Great, thanks!

**Comment by Cegaiel** [comment]
I have submitted this on behalf of player, with permission.  See https://github.com/DashingStrike/Automato-ATITD/commit/e6eb28947a4c3eeb4228d06b06f49fd3f3f48a85

**Pull request closed without merging**
