### PR TITLE
Several macro updates.

### PR DESCRIPTION
**Pull request by Manon120184**
Updated cc_Assist, cc_Auto, gather and wood macro's to work with T8. Had to add new cc images as it refused to work with old ones even when updated. Added dirt image for statclicks as it was missing. Updated images needed for wood macro. Created new default routes for gather macro for use in T8.

### CODE REVIEW

**Comment by ldobson** [comment]
Fixes #110

**Comment by taralx** [comment]
Hm, tested the new macro. Fine except it doesn't apply water at the end, so my batch burned up after green progress was hit.

**Comment by ldobson** [comment]
Can you try a couple more times, making sure you have a few jugs? I've run this a few times now with multiple hearths with no issues.

**Comment by taralx** [comment]
I did have jugs, but I suspect the existing water rule is too conservative -- if there is a pixel of water it will not add any. I've proposed some adjustments in #116.

**Pull request merged**
