### PR TITLE
Readd missing config_thistle.txt file

### PR DESCRIPTION
**Pull request by Aoreias**

### CODE REVIEW

**Comment by Jimbly** [comment]
Huh, sorry I missed that when migrating stuff!

Also, side-note: looks like pushing out updates was down due to an issue on my new server for the past couple weeks, I have fixed it now, and users should get this (and the last couple) PRs now.

**Comment by Aoreias** [comment]
Awesome :) You still have to trigger a build for the executable to find the
latest script updates to master, right?

**Comment by Jimbly** [comment]
No, script updates to master should go out automatically (github sends a web hook to my server, within seconds of it being merged you should see http://dashingstrike.com/Automato/games/ATITD/version.txt have the hash of the latest commit and be able to update to it), the only thing that is manual is if we make changes to the C++ code, making a new .EXE go out is manual.

**Comment by Aoreias** [comment]
Oh, sweet. Good to know :)

**Pull request merged**
