### PR TITLE
epbs.lua

### PR DESCRIPTION
**Pull request by safa**
Intended for microphone moderators to use. Does various modding tasks using Automato UI or keyboard shortcuts. Notifies when new posts are present.

### CODE REVIEW

**Comment by Jimbly** [comment]
I think you need to not include pbslog.txt (just add it to the .gitignore, probably), otherwise people will get changes to it and accidentally commit those changes, or every time they do an update, it'll reset it to what was committed.

Admittedly I haven't used ATITD in years, but "epbs" means nothing to me, is there a better name to use?

**Comment by Jimbly** [comment]
Also, did you make those images?  If so, they look great, if not, please include some attribution (even if just in the PR comments) as to what site they're from, assuming they're free to use in open source projects =).

**Comment by safa** [comment]
Right, didn't think about pbslog.txt that way :)  epbs stands for "Egyptian Public Broadcasting System". This telling game wide mic is called "Egypt Today" but i don't think that would be a good name either. How do you feel about mod_assist? (moderator.lua already exist) 

Images come from two sources:
Iconset: Long Shadow Media Icons by PelFusion
Artist: PelFusion
Iconset Homepage: http://pelfusion.com/media-long-shadow-icons
License: Linkware (Backlink to http://www.pelfusion.com required)
Commercial usage: Allowed

Iconset: Small & Flat Icons by paomedia
Artist: paomedia (Arnaud)
Iconset Homepage: https://github.com/paomedia/small-n-flat
License: Public Domain
Commercial usage: Allowed

**Comment by Jimbly** [comment]
That name sounds fine =).

For the icons that require attribution, probably best to make a change to README.md and add an attribution section at the bottom like:
```md
Attribution
-----------
Some icons from blah blah
```

**Comment by safa** [comment]
Done :)

**Comment by Aoreias** [comment]
Little late on this, but can you apply a consistent indentation style? Thanks :)

**Comment by safa** [comment]
I'm away from any computer at the moment. Will do later today :)

**Pull request merged**
