### PR TITLE
cc_auto tweaks

### PR DESCRIPTION
**Pull request by taralx**
* Allow oxygen to float higher when heat is below progress level.
* Aggressively add water after completion to avoid burning a successful batch.
* Adjust water threshold to be slightly more conservative.

### CODE REVIEW

**Comment by taralx** [comment]
* Also reduce wood level slightly to improve efficiency.

**Comment by Cegaiel** [comment]
Did I do something wrong?  This isn't lighting up the Update button on Automato ...

**Comment by Jimbly** [comment]
I don't think there's anything you could have done wrong, it appears there was an error on my server pushing out the patch, I'm looking into it.

**Comment by Jimbly** [comment]
Okay, issue resolved.  Turns out the cause had been sitting around for a long time and finally bit us - there's a .gitattributes file that specified text files should be "auto" which means CRLF on Windows, LF on Linux, when checked out locally, but LF in the repository, but there were a bunch of files which were still CRLF in the repository, so when one of those got checked out, on Linux (where the server runs), it got "modified", making it look like it had local changes, and messed things up.  I checked out the entire repo and re-committed it, which should have normalized the line endings, and should stop this from happening again.  Changes have now been pushed to users.  As a side effect, the line endings on users' computers are, I think, LF, since it comes from the patch made under Linux, maybe we should change that setting to text=CRLF instead to keep things consistent?

Side note: Git and Line Endings is one of the worst things ever...

**Comment by Cegaiel** [comment]
Thanks for fixing it so quickly.  I honestly can't answer your question about the CRLF setting. You know better than I :)

**Comment by taralx** [comment]
I don't think it will reoccur now that it's fixed. You can always add a hook to normalize if you're concerned.

**Pull request merged**
